# Generated by Django 4.2.4 on 2024-03-16 08:12

import articles.models
import django.core.serializers.json
from django.db import migrations, models
import django_pydantic_field.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "content_items",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default={"items": []},
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=articles.models.ArticleContentItems,
                    ),
                ),
            ],
        ),
    ]
