# fly.toml app configuration file generated for halcyon-backend on 2023-09-01T14:01:12+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "halcyon-backend"
primary_region = "cdg"
console_command = "/code/manage.py shell_plus"

[build]

[deploy]
  release_command = "sh ./deployment/release.sh"

[env]
  PORT = "8000"
  ALLOWED_HOSTS="localhost,127.0.0.1,halcyon-backend.fly.dev"
  DEBUG="False"
  ENVIRONMENT = "production"
  CSRF_TRUSTED_ORIGINS="https://halcyon-backend.fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "static/"
