# Generated by Django 4.2.4 on 2023-08-15 18:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="YogaCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="YogaChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("benefits_description", models.TextField()),
                ("cover_image_url", models.URLField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="YogaPose",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("sanskrit_name", models.CharField(help_text="Name in sanskrit language", max_length=255)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "chakras",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Muladhara", "Muladhara"),
                                ("Svadhishthana", "Svadhishthana"),
                                ("Manipura", "Manipura"),
                                ("Anahata", "Anahata"),
                                ("Vishuddha", "Vishuddha"),
                                ("Ajna", "Ajna"),
                                ("Sahasrara", "Sahasrara"),
                            ],
                            max_length=64,
                        ),
                        default=list,
                        null=True,
                        size=7,
                    ),
                ),
                ("audio_url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("categories", models.ManyToManyField(blank=True, to="yoga_practices.yogacategory")),
                ("muscle_groups", models.ManyToManyField(blank=True, to="yoga_practices.musclegroup")),
            ],
        ),
        migrations.CreateModel(
            name="YogaPractice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("benefits_description", models.TextField()),
                ("cover_image_url", models.URLField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="YogaStyle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="YogaPracticePose",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "yoga_pose",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_practices.yogapose"),
                ),
                (
                    "yoga_practice",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_practices.yogapractice"),
                ),
            ],
            options={
                "ordering": ["order", "yoga_practice__title"],
                "unique_together": {("yoga_practice", "order")},
            },
        ),
        migrations.AddField(
            model_name="yogapractice",
            name="yoga_poses",
            field=models.ManyToManyField(through="yoga_practices.YogaPracticePose", to="yoga_practices.yogapose"),
        ),
        migrations.AddField(
            model_name="yogapose",
            name="styles",
            field=models.ManyToManyField(blank=True, to="yoga_practices.yogastyle"),
        ),
        migrations.CreateModel(
            name="YogaChallengePractice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "yoga_challenge",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_practices.yogachallenge"),
                ),
                (
                    "yoga_practice",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_practices.yogapractice"),
                ),
            ],
            options={
                "ordering": ["order", "yoga_challenge__title"],
                "unique_together": {("yoga_challenge", "order")},
            },
        ),
        migrations.AddField(
            model_name="yogachallenge",
            name="practices",
            field=models.ManyToManyField(
                through="yoga_practices.YogaChallengePractice", to="yoga_practices.yogapractice"
            ),
        ),
    ]
