# Generated by Django 4.2.4 on 2023-08-13 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="YogaPose",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("sanskrit_name", models.CharField(help_text="Name in sanskrit language", max_length=255)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("audio_url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("muscle_groups", models.ManyToManyField(blank=True, null=True, to="yoga_practices.musclegroup")),
            ],
        ),
        migrations.CreateModel(
            name="YogaPractice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("benefits_description", models.TextField()),
                ("cover_image_url", models.URLField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="YogaPracticePose",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "yoga_pose",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_practices.yogapose"),
                ),
                (
                    "yoga_practice",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_practices.yogapractice"),
                ),
            ],
            options={
                "ordering": ["order", "yoga_practice__title"],
                "unique_together": {("yoga_practice", "order")},
            },
        ),
        migrations.AddField(
            model_name="yogapractice",
            name="yoga_poses",
            field=models.ManyToManyField(through="yoga_practices.YogaPracticePose", to="yoga_practices.yogapose"),
        ),
    ]
