# Generated by Django 4.2.4 on 2023-08-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yoga_practices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yogapose",
            name="muscle_groups",
            field=models.ManyToManyField(blank=True, to="yoga_practices.musclegroup"),
        ),
    ]
