# Generated by Django 4.2.4 on 2023-08-18 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yoga_practices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yogapose",
            name="duration",
            field=models.IntegerField(
                default=0, help_text="duration in seconds", validators=[django.core.validators.MinValueValidator(1)]
            ),
            preserve_default=False,
        ),
    ]
