# Generated by Django 4.2.4 on 2023-08-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yoga_practices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musclegroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
