# Generated by Django 4.2.4 on 2023-08-22 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("yoga_practices", "0002_alter_musclegroup_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yogapractice",
            options={"ordering": ["-created_at"]},
        ),
    ]
