# Generated by Django 4.2.4 on 2023-09-03 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("yoga_journeys", "0003_alter_journeyactiveyogachallenge_unique_together_and_more"),
        ("yoga_practices", "0003_alter_yogapractice_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneyCompletedYogaPractice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "yoga_journey",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_journeys.yogajourney"),
                ),
                (
                    "yoga_practice",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_practices.yogapractice"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JourneyActiveYogaChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_yoga_practices", models.ManyToManyField(to="yoga_practices.yogapractice")),
                (
                    "yoga_challenge",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_practices.yogachallenge"),
                ),
                (
                    "yoga_journey",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_journeys.yogajourney"),
                ),
            ],
            options={
                "ordering": ["-activated_at"],
                "unique_together": {("yoga_challenge", "yoga_journey")},
            },
        ),
    ]
