# Generated by Django 4.2.4 on 2023-09-03 14:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YogaLesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("cover_image_url", models.URLField(blank=True, null=True)),
                (
                    "priority",
                    models.IntegerField(
                        help_text="Used as an ordering criteria",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["-priority"],
            },
        ),
        migrations.CreateModel(
            name="YogaLessonStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "duration",
                    models.IntegerField(
                        help_text="duration in seconds", validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("audio_url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "yoga_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="yoga_lessons.yogalesson"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
