# Generated by Django 4.2.4 on 2024-03-17 07:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("yoga_practices", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("yoga_journeys", "0002_initial"),
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YogaLesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("cover_image_url", models.URLField(blank=True, null=True)),
                (
                    "priority",
                    models.IntegerField(
                        help_text="Used as an ordering criteria",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["-priority"],
            },
        ),
        migrations.CreateModel(
            name="YogaLessonStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "yoga_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="yoga_lessons.yogalesson"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="YogaLessonPracticeStep",
            fields=[
                (
                    "yogalessonstep_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="yoga_lessons.yogalessonstep",
                    ),
                ),
                (
                    "yoga_practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yoga_step_practices",
                        to="yoga_practices.yogapractice",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("yoga_lessons.yogalessonstep",),
        ),
        migrations.CreateModel(
            name="YogaLessonArticleStep",
            fields=[
                (
                    "yogalessonstep_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="yoga_lessons.yogalessonstep",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yoga_step_articles",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("yoga_lessons.yogalessonstep",),
        ),
        migrations.CreateModel(
            name="JourneyActiveYogaLesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_lesson_steps", models.ManyToManyField(to="yoga_lessons.yogalessonstep")),
                (
                    "yoga_journey",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_journeys.yogajourney"),
                ),
                (
                    "yoga_lesson",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_lessons.yogalesson"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("yoga_lesson", "yoga_journey")},
            },
        ),
    ]
