# Generated by Django 4.2.4 on 2023-09-04 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("yoga_journeys", "0004_alter_yogajourney_active_yoga_challenges_and_more"),
        ("yoga_lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneyActiveYogaLesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_lesson_steps", models.ManyToManyField(to="yoga_lessons.yogalessonstep")),
                (
                    "yoga_journey",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_journeys.yogajourney"),
                ),
                (
                    "yoga_lesson",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_lessons.yogalesson"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("yoga_lesson", "yoga_journey")},
            },
        ),
    ]
