# Generated by Django 4.2.4 on 2024-04-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("yoga_lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journeyactiveyogalesson",
            name="yoga_lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_yoga_lessons",
                to="yoga_lessons.yogalesson",
            ),
        ),
    ]
