# Generated by Django 4.2.4 on 2023-08-20 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("yoga_practices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneyCompletedYogaPractice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="YogaJourney",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_yoga_practices",
                    models.ManyToManyField(
                        blank=True,
                        through="yoga_journeys.JourneyCompletedYogaPractice",
                        to="yoga_practices.yogapractice",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="journeycompletedyogapractice",
            name="yoga_journey",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_journeys.yogajourney"),
        ),
        migrations.AddField(
            model_name="journeycompletedyogapractice",
            name="yoga_practice",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="yoga_practices.yogapractice"),
        ),
    ]
