# Generated by Django 4.2.4 on 2024-03-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("yoga_practices", "0001_initial"),
        ("yoga_journeys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yogajourney",
            name="active_yoga_challenges",
            field=models.ManyToManyField(
                blank=True, through="yoga_practices.JourneyActiveYogaChallenge", to="yoga_practices.yogachallenge"
            ),
        ),
    ]
