# Generated by Django 4.2.4 on 2024-03-17 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("yoga_practices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("yoga_lessons", "0001_initial"),
        ("yoga_journeys", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yogajourney",
            name="active_yoga_lessons",
            field=models.ManyToManyField(
                blank=True, through="yoga_lessons.JourneyActiveYogaLesson", to="yoga_lessons.yogalesson"
            ),
        ),
        migrations.AddField(
            model_name="yogajourney",
            name="completed_yoga_practices",
            field=models.ManyToManyField(
                blank=True, through="yoga_practices.JourneyCompletedYogaPractice", to="yoga_practices.yogapractice"
            ),
        ),
        migrations.AddField(
            model_name="yogajourney",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
