# Generated by Django 4.2.4 on 2023-09-03 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("yoga_journeys", "0002_journeyactiveyogachallenge_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="journeyactiveyogachallenge",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="journeyactiveyogachallenge",
            name="completed_yoga_practices",
        ),
        migrations.RemoveField(
            model_name="journeyactiveyogachallenge",
            name="yoga_challenge",
        ),
        migrations.RemoveField(
            model_name="journeyactiveyogachallenge",
            name="yoga_journey",
        ),
        migrations.RemoveField(
            model_name="journeycompletedyogapractice",
            name="yoga_journey",
        ),
        migrations.RemoveField(
            model_name="journeycompletedyogapractice",
            name="yoga_practice",
        ),
    ]
