# Generated by Django 4.2.4 on 2023-09-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yoga_lessons", "0002_journeyactiveyogalesson"),
        ("yoga_journeys", "0004_alter_yogajourney_active_yoga_challenges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="yogajourney",
            name="active_yoga_lessons",
            field=models.ManyToManyField(
                blank=True, through="yoga_lessons.JourneyActiveYogaLesson", to="yoga_lessons.yogalesson"
            ),
        ),
    ]
